# NumPy

## Tworzenie tablic

Funkcje tworzące tablice `ndarray`.

- `array(object, dtype)` - tworzenie tablicy z obiektu (np. listy)
- `linspace(start, stop, num)` - tworzenie tablicy liczb równorozłozonych (te same odstępy) w zadanym zakresie
- `logspace(start, stop, num)` - tworzenia tablicy liczb rozłozonych według skali logarytmicznej (kolejne potęgi liczby 10)
- `arange(start, stop, step)` - tworzenie tablicy ciągu liczb
- `zeros(size)` - tworzenie tablicy wypełnionej zerami
- `ones(size)` - tworzenie tablicy wypełnionej jedynkami

`ndarray.dtype` - atrybut do sprawdzania typu danych w tablicy

## Typy danych w tablicach

Jeśli typ danych nie jest podany z góry, jest on odgadywany.

Typy danych:
- `int32`, `int64`, `int16, `int8`, `int` - liczby całkowite
- `float64`, `float32`, `float16`, `float` - liczby zmiennoprzecinkowe
- `str_` - łańcuchy znaków
- `bool_` - wartości logiczne
- `object_` - mieszane typy danych (utrata szybkości obliczeniowej NumPy)

Liczba przy typie danych oznacza liczbe bajtów alokowanych w pamięci do przechowywania tablicy, oznacza to rowniez mozliwe zakres liczb przechowywanych w pamięci.

`numpy.astype()` - funkcja do zmiany typu danych w tablicy

## Atrybuty tablic

Atrybuty tablic:
- `ndarray.ndim` - wymiar tablicy
- `ndarray.shape` - liczb elementów w kazdym wymiarze (np. liczb wierszy i kolumn)
- `ndarray.size` - liczba wszystkim elementów w tablicy
- `ndarray.dtype` - typ danych w tablicy
- `ndarray.itemsize` - rozmiar w bajtach elementów tablicy

### Zadania

**Zadanie 1: Generowanie ciągów i podstawowe atrybuty (Poziom: Rozgrzewka)**

**Opis:** Wygeneruj jednowymiarową strukturę danych zawierającą wyłącznie parzyste liczby całkowite, zaczynając od wartości dziesięć, a kończąc na pięćdziesięciu włącznie. Po jej utworzeniu, wyciągnij z niej informacje o liczbie elementów (długości struktury) oraz zweryfikuj jej domyślny typ liczbowy.

* **Oczekiwane dane wejściowe:** Brak (generowanie od zera).
* **Oczekiwany rezultat:**
* Kształt struktury: (21,)
* Wartości: Sekwencja od dziesięciu do pięćdziesięciu (krok co dwa).
* Odpytane atrybuty: Całkowity rozmiar (wynik to 21) oraz typ danych (domyślny typ całkowitoliczbowy, zazwyczaj 64-bitowy na nowoczesnych maszynach).

In [1]:
import numpy as np

arr = np.arange(10, 51, 2)
print(f"Tablica: {arr}")
print(f"Liczba elementów: {arr.size}")
print(f"Typ danych: {arr.dtype}")

Tablica: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Liczba elementów: 21
Typ danych: int64


**Zadanie 2: Alokacja przestrzeni pod obraz i rygor typowania (Poziom: Łatwy)**

**Opis:** Zainicjuj trójwymiarową przestrzeń wypełnioną całkowicie zerami. Przestrzeń ta ma symulować pusty obraz cyfrowy RGB o rozdzielczości 256 na 256 pikseli (trzy kanały kolorów). Kluczowym wymogiem jest tutaj bezwzględna optymalizacja pamięciowa w momencie tworzenia. Przepływ danych wymaga, aby wartości w tej strukturze nigdy nie były ujemne i nie przekraczały wartości 255.

* **Oczekiwane dane wejściowe:** Brak.
* **Oczekiwany rezultat:**
* Kształt struktury: (256, 256, 3)
* Typ danych: Ośmiobitowa liczba całkowita bez znaku.

In [2]:
arr = np.zeros((256, 256, 3), dtype=np.uint8)
print(f"Tablica: {arr}")
print(f"Kształt tablic: {arr.shape}")
print(f"typ danych: {arr.dtype}")

Tablica: [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Kształt tablic: (256, 256, 3)
typ danych: uint8


**Zadanie 3: Precyzyjna dystrybucja i wypełnianie skalarne (Poziom: Średni)**

**Opis:** Zaprojektuj dwuwymiarową macierz składającą się z sześciu wierszy i pięciu kolumn. Pierwsze cztery wiersze mają zostać natychmiastowo wypełnione stałą wartością zmiennoprzecinkową równą dokładnie 7.25. Pozostałe dwa wiersze muszą stanowić jedną, ciągłą sekwencję (rozciągniętą przez wszystkie dziesięć komórek w tych dwóch wierszach), która zawiera równe, liniowo rozłożone odstępy między wartością zero a jeden włącznie. Zbuduj tę strukturę za pomocą dwóch osobnych operacji generowania, a następnie połącz je w jedną.

* **Oczekiwane dane wejściowe:** Brak.
* **Oczekiwany rezultat:**
* Kształt struktury ostatecznej: (6, 5)
* Typ danych: Zmiennoprzecinkowy.

In [ ]:
arr = np.empty((6, 5))
# print(arr)
arr[:4] = 7.25
# print(arr)
arr[4:] = np.linspace(0, 1, 10).reshape((2, 5))
print(arr)

[[7.25 7.25 7.25 7.25 7.25]
 [7.25 7.25 7.25 7.25 7.25]
 [7.25 7.25 7.25 7.25 7.25]
 [7.25 7.25 7.25 7.25 7.25]
 [0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.  ]]
[[7.25 7.25 7.25 7.25 7.25]
 [7.25 7.25 7.25 7.25 7.25]
 [7.25 7.25 7.25 7.25 7.25]
 [7.25 7.25 7.25 7.25 7.25]
 [0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.  ]]
[[7.25       7.25       7.25       7.25       7.25      ]
 [7.25       7.25       7.25       7.25       7.25      ]
 [7.25       7.25       7.25       7.25       7.25      ]
 [7.25       7.25       7.25       7.25       7.25      ]
 [0.         0.11111111 0.22222222 0.33333333 0.44444444]
 [0.55555556 0.66666667 0.77777778 0.88888889 1.        ]]


**Zadanie 4: Transformacje logiki na precyzję i analiza wagi (Poziom: Trudny)**

**Opis:** Zbuduj kwadratową macierz jednostkową (jedynki na głównej przekątnej, zera w pozostałych miejscach) o rozmiarze 500 na 500. Konstruując ją, wymuś, aby początkowo składała się wyłącznie z wartości logicznych (prawda/fałsz). Krok drugi polega na nadpisaniu tej struktury poprzez bezwzględną konwersję jej typu do zmiennoprzecinkowego o sztucznie obniżonej precyzji (trzydzieści dwa bity). Ostatnim krokiem jest odpytanie atrybutu, który zwróci dokładną wartość w bajtach, jaką ta finalna macierz zajmuje w pamięci operacyjnej.

* **Oczekiwane dane wejściowe:** Brak.
* **Oczekiwany rezultat:**
* Kształt struktury początkowej i końcowej: (500, 500).
* Typ końcowy: 32-bitowy zmiennoprzecinkowy.
* Rozmiar w pamięci: Równo milion bajtów.

In [ ]:
arr = np.identity(500, dtype=np.bool_)
arr = arr.astype(np.float32)
print(f"Liczba zajmowanych bajtów: {arr.nbytes}")

Liczba zajmowanych bajtów: 1000000


**Zadanie 5: Alokacja błyskawiczna i audyt metadanych w domenie zespolonej (Poziom: Ekspert)**

**Opis:** Zarezerwuj w pamięci przestrzeń pod macierz o wymiarach 100 na 50, ale zrób to w sposób gwarantujący najszybszy możliwy czas wykonania – struktura nie może być inicjowana żadnymi konkretnymi wartościami (w pamięci mają zostać tak zwane "śmieci"). Wymuś na etapie tworzenia, by traktowała ona dane jako liczby zespolone o standardowej, podwójnej precyzji. Bezpośrednio po rezerwacji, używając wyłącznie wbudowanych atrybutów struktury, wyciągnij cztery metadane i przypisz je do jednej kolekcji: liczbę wymiarów struktury, pełny wektor kształtu, rozmiar w bajtach pojedynczego elementu oraz całkowitą wagę struktury w bajtach.

* **Oczekiwane dane wejściowe:** Brak.
* **Oczekiwany rezultat:**
* Kształt struktury: (100, 50).
* Typ: Liczba zespolona bazująca na 64-bitowych składowych zmiennoprzecinkowych (całkowity rozmiar elementu to 128 bitów).
* Wynikowa kolekcja metadanych (kolejno): Wartość dwa; wektor (100, 50); szesnaście; osiemdziesiąt tysięcy.

In [7]:
arr = np.empty((100, 50), dtype=np.complex128)
attributes = {
    "wymiary": arr.ndim,
    "kształt": arr.shape,
    "rozmiar_elementu": arr.itemsize,
    "rozmiar_tablicy": arr.nbytes,
}

for attr, value in attributes.items():
    print(attr, ": ", value)

wymiary :  2
kształt :  (100, 50)
rozmiar_elementu :  16
rozmiar_tablicy :  80000
